### ISSUE TITLE
upon running CMakeGUI on this repo's clone in my hard drive, I get "Could NOT find WrapVulkanHeaders (missing: Vulkan_INCLUDE_DIR)" 

### ISSUE THREAD

**Issue by juandent** [villevoutilainen/ProgrammingPrinciplesAndPracticeUsingQt#8]
running CMakeGUI on this repo's clone in my hard drive returns an error " Could NOT find WrapVulkanHeaders (missing: Vulkan_INCLUDE_DIR)"  

What is this and how do I fix it?

Regards,
Juan

**Comment by villevoutilainen** [comment]
You need to set CMAKE_PREFIX_PATH to point to where Qt's cmake scripts are. See https://doc.qt.io/qt-6/cmake-build-on-cmdline.html

**Comment by villevoutilainen** [comment]
May I ask why you are trying to use CMakeGUI, instead of using MS Visual Studio or Qt Creator? Both of those set the prefix automatically once they have been configured with the proper Qt version, which for Visual Studio is a relatively easy operation, and for Qt Creator it's automatic, the installation will just do it.
